# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
